# prometheus.prometheusSpec.additionalArgs
prometheus:
  prometheusSpec:
    additionalArgs:
      - name: web.enable-otlp-receiver
        value: ""

grafana:
  plugins:
    - fetzerch-sunandmoon-datasource
    - yesoreyeram-infinity-datasource
    - digrich-bubblechart-panel
    - grafana-clock-panel