apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-app-version
spec:
  template:
    spec:
      containers:
        - name: kube-app-version
          image: ghcr.io/joostvdg/kube-app-version:0.5.5@sha256:4a855b72db622f8e4bc544c25ef813ddedbf781cdcf2bc1d020764df1e277977
          env:
            - name: APP_REDIS_MODE
              value: "OPTIONAL"
            - name: APPS_COLLECT_ON_STARTUP
              value: "true"
            - name: VERSIONS_REFRESH_ON_STARTUP
              value: "false"
            - name: VERSIONS_INTERVAL_MILLIS
              value: "600000" # 3600000 = 1 hour, 10 minutes = 600000
            - name: VERSIONS_CACHE_VALIDITY_MINUTES
              value: "20"
            - name: LOGGING_LEVEL_net_joostvdg_kube_app_version
              value: "DEBUG"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: token
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
