apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-app-version
spec:
  template:
    spec:
      containers:
        - name: kube-app-version
          image: ghcr.io/joostvdg/kube-app-version:0.1.0@sha256:d2e7bae73d33bfdcfef17981562145bf71ec2262d98fad6005fe13597b9357a7
          env:
            - name: APP_REDIS_MODE
              value: "OPTIONAL"
