app:
  version:
    outdated-artifacts:
      collect-on-startup: ${APPS_COLLECT_ON_STARTUP:true}
      refresh-on-startup: ${VERSIONS_REFRESH_ON_STARTUP:true}
      interval-ms: ${VERSIONS_INTERVAL_MILLIS:3600000} # 3600000 = 1 hour
      cache-validity-minutes: ${VERSIONS_CACHE_VALIDITY_MINUTES:60}
  kubernetes:
    mode: ${KUBERNETES_MODE:DIRECT}
    kubeconfig-path: ${KUBERNETES_KUBECONFIG_PATH:}
    context-name: ${KUBERNETES_CONTEXT_NAME:}
    cluster-name: ${KUBERNETES_CLUSTER_NAME:local}
    cluster-endpoint: ${KUBERNETES_CLUSTER_ENDPOINT:127.0.0.1:443}
  redis:
    mode: ${REDIS_MODE:OPTIONAL}
    reconnectInterval: ${REDIS_RECONNECT_INTERVAL:60000}

logging:
  level:
    net:
      joostvdg:
        kube_app_version: DEBUG

cluster:
  name: "local"
  url: "127.0.0.1:443"

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Kubernetes App Version Info
  threads:
    virtual:
      enabled: true
  cache:
    type: caffeine


  data:
    redis:
      repositories:
        enabled: true
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      timeout: 2000
      password: ${REDIS_PASSWORD:notasecret}
#      database: 0
#      cluster:
#        nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381

management:
  tracing:
    sampling:
      probability: '1.0'
  otlp:
    tracing:
      endpoint: http://otel-collector-opentelemetry-collector.default.svc.cluster.local:4318/v1/traces
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: "health,info"
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

  endpoint:
    info:
      enabled: true
    health:
      probes:
        enabled: true
        add-additional-paths=true:
          enabled: true
          additional-paths: "/liveness, /readiness"