apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: keycloak
    repoURL: oci://registry-1.docker.io/bitnamicharts
    targetRevision: "24.7.1"