apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-app-version
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joostvdg/kube-app-version.git
    targetRevision: main
    path: kubernetes/kustomize/overlays/kind
    kustomize:
      namePrefix: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: kav
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true