apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-app-version
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-app-version
  template:
    metadata:
      labels:
        app: kube-app-version
    spec:
      serviceAccountName: kube-app-version
      containers:
        - name: kube-app-version
          image: ghcr.io/joostvdg/kube-app-version:0.1.0@sha256:d2e7bae73d33bfdcfef17981562145bf71ec2262d98fad6005fe13597b9357a7
          ports:
            - containerPort: 8080
          env:
            - name: APP_REDIS_MODE
              value: "REQUIRED"
            - name: KUBERNETES_MODE
              value: "IN_CLUSTER"
          # Startup probe - allows application to fully start before other probes begin
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 30
          # Liveness probe - detects if application is running
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          # Readiness probe - detects if application is ready to serve requests
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3